### ISSUE TITLE
Module not found

### ISSUE THREAD

**Issue by PierreScerri** [zachowj/hass-node-red#120]
## Configuration

```yaml

Add your logs here.

```

## Describe the bug
After updating from 11.0.0 to 11.0.1, the node-red-contrib-modbus pallette is reporting 'Module not found'.  All flows are stopped.

## Debug log

```text

Add your logs here.
- /opt/node_modules/node-red-contrib-modbus/modbus/modbus-flex-getter.js
- /opt/node_modules/@node-red/registry/lib/loader.js
- /opt/node_modules/@node-red/registry/lib/index.js
- /opt/node_modules/@node-red/runtime/lib/nodes/index.js
- /opt/node_modules/@node-red/runtime/lib/index.js
- /opt/node_modules/node-red/lib/red.js
- /opt/node_modules/node-red/red.js
15 Feb 09:21:42 - [warn] [node-red-contrib-modbus/Modbus-Write] Error: Cannot find module 'source-map-support'
Require stack:
- /opt/node_modules/node-red-contrib-modbus/modbus/modbus-write.js
- /opt/node_modules/@node-red/registry/lib/loader.js
- /opt/node_modules/@node-red/registry/lib/index.js
- /opt/node_modules/@node-red/runtime/lib/nodes/index.js
- /opt/node_modules/@node-red/runtime/lib/index.js
- /opt/node_modules/node-red/lib/red.js
- /opt/node_modules/node-red/red.js
15 Feb 09:21:42 - [warn] [node-red-contrib-modbus/Modbus-Flex-Write] Error: Cannot find module 'source-map-support'
Require stack:
- /opt/node_modules/node-red-contrib-modbus/modbus/modbus-flex-write.js
- /opt/node_modules/@node-red/registry/lib/loader.js
- /opt/node_modules/@node-red/registry/lib/index.js
- /opt/node_modules/@node-red/runtime/lib/nodes/index.js
- /opt/node_modules/@node-red/runtime/lib/index.js
- /opt/node_modules/node-red/lib/red.js
- /opt/node_modules/node-red/red.js
15 Feb 09:21:42 - [warn] [node-red-contrib-modbus/Modbus-Server] Error: Cannot find module 'source-map-support'
Require stack:
- /opt/node_modules/node-red-contrib-modbus/modbus/modbus-server.js
- /opt/node_modules/@node-red/registry/lib/loader.js
- /opt/node_modules/@node-red/registry/lib/index.js
- /opt/node_modules/@node-red/runtime/lib/nodes/index.js
- /opt/node_modules/@node-red/runtime/lib/index.js
- /opt/node_modules/node-red/lib/red.js
- /opt/node_modules/node-red/red.js
15 Feb 09:21:42 - [warn] [node-red-contrib-modbus/Modbus-Flex-Server] Error: Cannot find module 'source-map-support'
Require stack:
- /opt/node_modules/node-red-contrib-modbus/modbus/modbus-flex-server.js
- /opt/node_modules/@node-red/registry/lib/loader.js
- /opt/node_modules/@node-red/registry/lib/index.js
- /opt/node_modules/@node-red/runtime/lib/nodes/index.js
- /opt/node_modules/@node-red/runtime/lib/index.js
- /opt/node_modules/node-red/lib/red.js
- /opt/node_modules/node-red/red.js
15 Feb 09:21:42 - [warn] [node-red-contrib-modbus/Modbus-Queue-Info] Error: Cannot find module 'source-map-support'
Require stack:
- /opt/node_modules/node-red-contrib-modbus/modbus/modbus-queue-info.js
- /opt/node_modules/@node-red/registry/lib/loader.js
- /opt/node_modules/@node-red/registry/lib/index.js
- /opt/node_modules/@node-red/runtime/lib/nodes/index.js
- /opt/node_modules/@node-red/runtime/lib/index.js
- /opt/node_modules/node-red/lib/red.js
- /opt/node_modules/node-red/red.js
15 Feb 09:21:42 - [warn] [node-red-contrib-modbus/Modbus-Flex-Connector] Error: Cannot find module 'source-map-support'
Require stack:
- /opt/node_modules/node-red-contrib-modbus/modbus/modbus-flex-connector.js
- /opt/node_modules/@node-red/registry/lib/loader.js
- /opt/node_modules/@node-red/registry/lib/index.js
- /opt/node_modules/@node-red/runtime/lib/nodes/index.js
- /opt/node_modules/@node-red/runtime/lib/index.js
- /opt/node_modules/node-red/lib/red.js
- /opt/node_modules/node-red/red.js
15 Feb 09:21:42 - [warn] [node-red-contrib-modbus/Modbus-IO-Config] Error: Cannot find module 'source-map-support'
Require stack:
- /opt/node_modules/node-red-contrib-modbus/modbus/modbus-io-config.js
- /opt/node_modules/@node-red/registry/lib/loader.js
- /opt/node_modules/@node-red/registry/lib/index.js
- /opt/node_modules/@node-red/runtime/lib/nodes/index.js
- /opt/node_modules/@node-red/runtime/lib/index.js
- /opt/node_modules/node-red/lib/red.js
- /opt/node_modules/node-red/red.js
15 Feb 09:21:42 - [warn] [node-red-contrib-modbus/Modbus-Response-Filter] Error: Cannot find module 'source-map-support'
Require stack:
- /opt/node_modules/node-red-contrib-modbus/modbus/modbus-response-filter.js
- /opt/node_modules/@node-red/registry/lib/loader.js
- /opt/node_modules/@node-red/registry/lib/index.js
- /opt/node_modules/@node-red/runtime/lib/nodes/index.js
- /opt/node_modules/@node-red/runtime/lib/index.js
- /opt/node_modules/node-red/lib/red.js
- /opt/node_modules/node-red/red.js
15 Feb 09:21:42 - [warn] [node-red-contrib-modbus/Modbus-Flex-Sequencer] Error: Cannot find module 'source-map-support'
Require stack:
- /opt/node_modules/node-red-contrib-modbus/modbus/modbus-flex-sequencer.js
- /opt/node_modules/@node-red/registry/lib/loader.js
- /opt/node_modules/@node-red/registry/lib/index.js
- /opt/node_modules/@node-red/runtime/lib/nodes/index.js
- /opt/node_modules/@node-red/runtime/lib/index.js
- /opt/node_modules/node-red/lib/red.js
- /opt/node_modules/node-red/red.js
15 Feb 09:21:42 - [warn] [node-red-node-rbe/rbe] 'rbe' already registered by module node-red
15 Feb 09:21:42 - [warn] ------------------------------------------------------
15 Feb 09:21:42 - [info] Settings file  : /etc/node-red/config.js
15 Feb 09:21:42 - [info] Context store  : 'default' [module=memory]
15 Feb 09:21:42 - [info] User directory : /config/node-red/
15 Feb 09:21:42 - [warn] Projects disabled : editorTheme.projects.enabled=false
15 Feb 09:21:42 - [info] Flows file     : /config/node-red/flows.json
15 Feb 09:21:42 - [info] Server now running at http://127.0.0.1:46836/
[09:21:42] INFO: Starting NGinx...
15 Feb 09:21:42 - [info] Waiting for missing types to be registered:
15 Feb 09:21:42 - [info]  - modbus-client
15 Feb 09:21:42 - [info]  - modbus-getter
```

**Comment by zachowj** [comment]
This is not the add-on repo.

<https://github.com/hassio-addons/addon-node-red>
