### ISSUE TITLE
Upgrade to 1.6.0: cannot import name 'HOME_ASSISTANT_AGENT' from 'homeassistant.components.conversation'

### ISSUE THREAD

**Issue by FileGo** [zachowj/hass-node-red#194]
## Version of the custom_component

NodeRED Companion: 1.6.0
HA: 2023.4.6
NodeRED: 14.3.0

## Describe the bug

Integration fails to load after upgrading from 1.4.0 to 1.6.0.

## Debug log

```text

Logger: homeassistant.setup
Source: setup.py:213
First occurred: 16:13:32 (1 occurrences)
Last logged: 16:13:32
Setup failed for custom integration nodered: Unable to import component: cannot import name 'HOME_ASSISTANT_AGENT' from 'homeassistant.components.conversation' (/usr/src/homeassistant/homeassistant/components/conversation/__init__.py)

```

**Comment by TuTunabh4** [comment]
yes,i've met the same question.How to fix that?

**Comment by TuTunabh4** [comment]
When I delete the intergation and install again,it shows the error" {"message":"Invalid handler specified"}"

**Comment by zachowj** [comment]
You're going to need to revert to version 1.4.0 if not running Home Assistant 2023.7+

**Comment by TuTunabh4** [comment]
Thank you so much. It has been fixed. And it looks like version 1.5.0 also can't work with Home Assistant 2023.1.

**Comment by zachowj** [comment]
Version 1.6.1 will now work Home Assistant versions back to 2021.12.0. Starting with v2.0.0, it will require Home Assistant 2023.7+.
